name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Ensure the GitHub Actions bot has write permissions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.0'  # Ensure a compatible Node.js version

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.14.5

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm run build

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .next/static # Update this to .next/static
        publish_branch: gh-pages